version: '3.8'

services:
  db-proprli:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      proprli_test_network:
        ipv4_address: 132.25.0.11  # IP específico para o PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data

  laravel-proprli:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:80"  # Porta do Apache dentro do contêiner é 80
    volumes:
      - .:/var/www/html
    depends_on:
      - db-proprli
    networks:
      - proprli_test_network

networks:
  proprli_test_network:
    driver: bridge
    ipam:
      config:
        - subnet: 132.25.0.0/16

volumes:
  postgres_data:
